### ISSUE TITLE
How was this fix made?

### ISSUE THREAD

**Issue by NayamAmarshe** [WIFIDarthMaul/Peter-Jackson-s-King-Kong-Signature-Edition-Fix#1]
Hi! I'm interested in knowing how you fixed the game. After 16 years we finally have a solution, been looking for it for a long time!

**Comment by WIFIDarthMaul** [comment]
> Hi! I'm interested in knowing how you fixed the game. After 16 years we finally have a solution, been looking for it for a long time!

Well to start off, I'm a huge fan of the game and own the Signature Edition on disc, i was trying to find a way for years too. This is the first time since 2005 that the game is fully playable, on any Windows version (even Windows 11 😉) without StarForce. The fix is based on modified PAL European region game executables with a command line attached to make it run. The game also would throw an error and would not launch if the game folder was moved from where it was originally installed. I counter-acted this with a simple registry fix, which you can see here:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{111E336D-30BF-4CD4-8D69-4541732AFB27}]
"ModifyPath"="RunDll32 C:\\PROGRA~2\\COMMON~1\\INSTAL~1\\PROFES~1\\RunTime\\11\\00\\Intel32\\Ctor.dll,LaunchSetup \"C:\\Program Files (x86)\\InstallShield Installation Information\\{111E336D-30BF-4CD4-8D69-4541732AFB27}\\setup.exe\" -l0x9 "
"UninstallString"="RunDll32 C:\\PROGRA~2\\COMMON~1\\INSTAL~1\\PROFES~1\\RunTime\\11\\00\\Intel32\\Ctor.dll,LaunchSetup \"C:\\Program Files (x86)\\InstallShield Installation Information\\{111E336D-30BF-4CD4-8D69-4541732AFB27}\\setup.exe\" -l0x9  -removeonly"
"LogFile"="C:\\Program Files (x86)\\InstallShield Installation Information\\{111E336D-30BF-4CD4-8D69-4541732AFB27}\\setup.ilg"
"InstallLocation"=".\\"
"InstallSource"="I:\\"
"ProductGuid"="{111E336D-30BF-4CD4-8D69-4541732AFB27}"
"DisplayName"="Peter Jackson's King Kong -The Official Game of the Movie"
"Publisher"="Ubisoft"
"URLInfoAbout"="http://www.Ubisoft.com"
"RegOwner"="Hakan"
"NoModify"=dword:00000000
"NoRemove"=dword:00000000
"NoRepair"=dword:00000001
"InstallDate"="20190210"
"Language"=dword:00000009
"DisplayVersion"="1.00.0000"
"Version"=dword:01000000
"MajorVersion"=dword:00000001
"MinorVersion"=dword:00000000
"LogMode"=dword:00000001

**Comment by NayamAmarshe** [comment]
> > Hi! I'm interested in knowing how you fixed the game. After 16 years we finally have a solution, been looking for it for a long time!
> 
> Well to start off, I'm a huge fan of the game and own the Signature Edition on disc, i was trying to find a way for years too. This is the first time since 2005 that the game is fully playable, on any Windows version (even Windows 11 ) without StarForce. The fix is based on modified PAL European region game executables with a command line attached to make it run. The game also would throw an error and would not launch if the game folder was moved from where it was originally installed. I counter-acted this with a simple registry fix, which you can see here:

Awesome! Thanks!

**Comment by NayamAmarshe** [comment]
@WIFIDarthMaul The game does not remember the graphics settings and defaults to the lowest, is there a fix for this?

**Comment by WIFIDarthMaul** [comment]
> @WIFIDarthMaul The game does not remember the graphics settings and defaults to the lowest, is there a fix for this?

Not that i know of, I've never ran into this issue. The game saves it's settings in the registry
